#!/bin/sh

# M109: Set Extruder Temperature and Wait 
# M109 in Marlin, Sprinter (ATmega port)
# Set extruder heater temperature in degrees celsius and wait for this
# temperature to be achieved.
# Example: M109 S185 

halcmd sets e0.temp.set $1

while [ "`halcmd gets e0.temp.ready`" != "TRUE" ]; do
  sleep .5
done

exit 0

