#!/bin/sh

# M190: Wait for bed temperature to reach target temp 
# Example: M190 S60
# This will wait until the bed temperature reaches 60 degrees, printing
# out the temperature of the hot end and the bed every second. 


halcmd sets bed.temp.set $1

while  [ "`halcmd gets bed.temp.ready`" != "TRUE" ]; do
  sleep .5
done

exit 0

